language: node_js
node_js:
  - "14"

cache: yarn

notifications:
  email:
    on_success: never
    on_failure: change
    recipients:
      - VDVUGaD@gmail.com

after_success:
  - yarn run coveralls
